/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectsoccerscout;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author oOo
 */
public class MatchPlayer extends javax.swing.JFrame {
     static ArrayList<String> PlayerList = new ArrayList<String>();
     static DefaultComboBoxModel<String> playermodel = new DefaultComboBoxModel<String>();
     static ArrayList<String> MatchPlayer = new ArrayList<String>();
     Integer SubCount = 0;
     Integer GKCount = 0;
     static ArrayList<Integer> Sub = new ArrayList<Integer>();
    /**
     * Creates new form MatchReport
     */
    public MatchPlayer() throws SQLException {

        if(MyConnection.getConnection()==null) {
            JOptionPane.showMessageDialog(null,"Cannot connect with the database");
            System.exit(0);
        }
        else
        {
        getList();
        initComponents();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        label5 = new java.awt.Label();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        P1 = new javax.swing.JComboBox<>();
        P2 = new javax.swing.JComboBox<>();
        P3 = new javax.swing.JComboBox<>();
        P4 = new javax.swing.JComboBox<>();
        P5 = new javax.swing.JComboBox<>();
        P6 = new javax.swing.JComboBox<>();
        Pos1 = new javax.swing.JComboBox<>();
        Pos2 = new javax.swing.JComboBox<>();
        Pos3 = new javax.swing.JComboBox<>();
        Pos4 = new javax.swing.JComboBox<>();
        Pos5 = new javax.swing.JComboBox<>();
        Pos6 = new javax.swing.JComboBox<>();
        P7 = new javax.swing.JComboBox<>();
        P8 = new javax.swing.JComboBox<>();
        P9 = new javax.swing.JComboBox<>();
        P10 = new javax.swing.JComboBox<>();
        P11 = new javax.swing.JComboBox<>();
        Pos7 = new javax.swing.JComboBox<>();
        Pos8 = new javax.swing.JComboBox<>();
        Pos9 = new javax.swing.JComboBox<>();
        Pos10 = new javax.swing.JComboBox<>();
        Pos11 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        PS1 = new javax.swing.JComboBox<>();
        PS2 = new javax.swing.JComboBox<>();
        PS3 = new javax.swing.JComboBox<>();
        PS4 = new javax.swing.JComboBox<>();
        PS5 = new javax.swing.JComboBox<>();
        PS6 = new javax.swing.JComboBox<>();
        PS7 = new javax.swing.JComboBox<>();
        Sub1 = new javax.swing.JRadioButton();
        Sub3 = new javax.swing.JRadioButton();
        Sub2 = new javax.swing.JRadioButton();
        Sub5 = new javax.swing.JRadioButton();
        Sub4 = new javax.swing.JRadioButton();
        Sub6 = new javax.swing.JRadioButton();
        Sub7 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        label1.setText("Match Opponent");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        label2.setText("Home/Away");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Home");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Away");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        label5.setText("Score(Your Team vs Opponent)\n");

        jTextField2.setText("0");

        jTextField3.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setText("Player");

        DefaultComboBoxModel<String> model1 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model1.addElement(PlayerList.get(i));
        }
        P1.setModel(model1);

        DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model2.addElement(PlayerList.get(i));
        }
        P2.setModel(model2);

        DefaultComboBoxModel<String> model3 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model3.addElement(PlayerList.get(i));
        }
        P3.setModel(model3);

        DefaultComboBoxModel<String> model4 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model4.addElement(PlayerList.get(i));
        }
        P4.setModel(model4);

        DefaultComboBoxModel<String> model5 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model5.addElement(PlayerList.get(i));
        }
        P5.setModel(model5);

        DefaultComboBoxModel<String> model6 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model6.addElement(PlayerList.get(i));
        }
        P6.setModel(model6);

        Pos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GK", "LB", "CB", "RB", "CDM", "CM", "RW", "LW", "CAM", "ST" }));

        Pos2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GK", "LB", "CB", "RB", "CDM", "CM", "RW", "LW", "CAM", "ST" }));

        Pos3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GK", "LB", "CB", "RB", "CDM", "CM", "RW", "LW", "CAM", "ST" }));

        Pos4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GK", "LB", "CB", "RB", "CDM", "CM", "RW", "LW", "CAM", "ST" }));

        Pos5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GK", "LB", "CB", "RB", "CDM", "CM", "RW", "LW", "CAM", "ST" }));

        Pos6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GK", "LB", "CB", "RB", "CDM", "CM", "RW", "LW", "CAM", "ST" }));

        DefaultComboBoxModel<String> model7 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model7.addElement(PlayerList.get(i));
        }
        P7.setModel(model7);

        DefaultComboBoxModel<String> model8 = new DefaultComboBoxModel<String>();

        for(int i = 0;i<PlayerList.size();i++)
        {
            model8.addElement(PlayerList.get(i));
        }
        P8.setModel(model8);

        DefaultComboBoxModel<String> model9 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model9.addElement(PlayerList.get(i));
        }
        P9.setModel(model9);

        DefaultComboBoxModel<String> model10 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model10.addElement(PlayerList.get(i));
        }
        P10.setModel(model10);

        DefaultComboBoxModel<String> model11 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model11.addElement(PlayerList.get(i));
        }
        P11.setModel(model11);

        Pos7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GK", "LB", "CB", "RB", "CDM", "CM", "RW", "LW", "CAM", "ST" }));

        Pos8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GK", "LB", "CB", "RB", "CDM", "CM", "RW", "LW", "CAM", "ST" }));

        Pos9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GK", "LB", "CB", "RB", "CDM", "CM", "RW", "LW", "CAM", "ST" }));

        Pos10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GK", "LB", "CB", "RB", "CDM", "CM", "RW", "LW", "CAM", "ST" }));

        Pos11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GK", "LB", "CB", "RB", "CDM", "CM", "RW", "LW", "CAM", "ST" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(P1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(P6, 0, 170, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Pos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Pos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Pos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Pos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P10, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Pos5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(P11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Pos6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pos7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(P11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pos6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setText("Substitute");

        DefaultComboBoxModel<String> model12 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model12.addElement(PlayerList.get(i));
        }
        PS1.setModel(model12);

        DefaultComboBoxModel<String> model13 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model13.addElement(PlayerList.get(i));
        }
        PS2.setModel(model13);

        DefaultComboBoxModel<String> model14 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model14.addElement(PlayerList.get(i));
        }
        PS3.setModel(model14);

        DefaultComboBoxModel<String> model15 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model15.addElement(PlayerList.get(i));
        }
        PS4.setModel(model15);

        DefaultComboBoxModel<String> model16 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model16.addElement(PlayerList.get(i));
        }
        PS5.setModel(model16);

        DefaultComboBoxModel<String> model17 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model17.addElement(PlayerList.get(i));
        }
        PS6.setModel(model17);

        DefaultComboBoxModel<String> model18 = new DefaultComboBoxModel<String>();
        for(int i = 0;i<PlayerList.size();i++)
        {
            model18.addElement(PlayerList.get(i));
        }
        PS7.setModel(model18);

        Sub1.setText("On");
        Sub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub1ActionPerformed(evt);
            }
        });

        Sub3.setText("On");

        Sub2.setText("On");

        Sub5.setText("On");

        Sub4.setText("On");

        Sub6.setText("On");

        Sub7.setText("On");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PS1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PS3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PS2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PS4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PS5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PS6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PS7, 0, 151, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PS1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PS3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PS4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PS5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PS6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PS7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton2.setText("Confirm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(295, 295, 295))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    
    private boolean checkRequirement(){
       MatchPlayer.add(P1.getItemAt(P1.getSelectedIndex()));
       MatchPlayer.add(P2.getItemAt(P2.getSelectedIndex()));
       MatchPlayer.add(P3.getItemAt(P3.getSelectedIndex()));
       MatchPlayer.add(P4.getItemAt(P4.getSelectedIndex()));
       MatchPlayer.add(P5.getItemAt(P5.getSelectedIndex()));
       MatchPlayer.add(P6.getItemAt(P6.getSelectedIndex()));
       MatchPlayer.add(P7.getItemAt(P7.getSelectedIndex()));
       MatchPlayer.add(P8.getItemAt(P8.getSelectedIndex()));
       MatchPlayer.add(P9.getItemAt(P9.getSelectedIndex()));
       MatchPlayer.add(P10.getItemAt(P10.getSelectedIndex()));
       MatchPlayer.add(P11.getItemAt(P11.getSelectedIndex()));
       MatchPlayer.add(PS1.getItemAt(PS1.getSelectedIndex()));
       MatchPlayer.add(PS2.getItemAt(PS2.getSelectedIndex()));
       MatchPlayer.add(PS3.getItemAt(PS3.getSelectedIndex()));
       MatchPlayer.add(PS4.getItemAt(PS4.getSelectedIndex()));
       MatchPlayer.add(PS5.getItemAt(PS5.getSelectedIndex()));
       MatchPlayer.add(PS6.getItemAt(PS6.getSelectedIndex()));
       MatchPlayer.add(PS7.getItemAt(PS7.getSelectedIndex()));
       for(int i = 0;i<17;i++){
           for(int j = i+1;j<17;j++)
           {
               if(MatchPlayer.get(i).equals(MatchPlayer.get(j)))
                   JOptionPane.showMessageDialog(null,"Duplicate player");
                    return false;
           }
       }
       if(Sub1.isSelected()) {
           SubCount++;
           Sub.add(getID(PS1.getItemAt(PS1.getSelectedIndex())));
           
       }
       if(Sub2.isSelected()) {SubCount++;
            Sub.add(getID(PS2.getItemAt(PS2.getSelectedIndex())));
       }
       if(Sub3.isSelected()) {SubCount++;
                         Sub.add(getID(PS3.getItemAt(PS3.getSelectedIndex())));

       }
       if(Sub4.isSelected()) {SubCount++;
                                Sub.add(getID(PS4.getItemAt(PS4.getSelectedIndex())));

       }
       if(Sub5.isSelected()){ SubCount++;
                              Sub.add(getID(PS5.getItemAt(PS5.getSelectedIndex())));
       }
       if(Sub6.isSelected()){ SubCount++;
                             Sub.add(getID(PS6.getItemAt(PS6.getSelectedIndex())));
       }
       if(Sub7.isSelected()) {SubCount++;
                              Sub.add(getID(PS7.getItemAt(PS7.getSelectedIndex())));
       }
       if(SubCount > 3){
            JOptionPane.showMessageDialog(null,"Out of sub,max 3");
            SubCount = 0;
            Sub.removeAll(Sub);
            return false;
       }
       if(Pos1.getItemAt(Pos1.getSelectedIndex()).equals("GK")) GKCount++;
       if(Pos2.getItemAt(Pos2.getSelectedIndex()).equals("GK")) GKCount++;
       if(Pos3.getItemAt(Pos3.getSelectedIndex()).equals("GK")) GKCount++;
       if(Pos4.getItemAt(Pos4.getSelectedIndex()).equals("GK")) GKCount++;
       if(Pos5.getItemAt(Pos5.getSelectedIndex()).equals("GK")) GKCount++;
       if(Pos6.getItemAt(Pos6.getSelectedIndex()).equals("GK")) GKCount++;
       if(Pos7.getItemAt(Pos7.getSelectedIndex()).equals("GK")) GKCount++;
       if(Pos8.getItemAt(Pos8.getSelectedIndex()).equals("GK")) GKCount++;
       if(Pos9.getItemAt(Pos9.getSelectedIndex()).equals("GK")) GKCount++;
       if(Pos10.getItemAt(Pos10.getSelectedIndex()).equals("GK")) GKCount++;
       if(Pos11.getItemAt(Pos11.getSelectedIndex()).equals("GK")) GKCount++;
       if(GKCount != 1){
           JOptionPane.showMessageDialog(null,"One goalkeeper and only one");
           GKCount = 0;
           return false;
       }
       if(jTextField1.getText().trim().equals(""))
       {
           JOptionPane.showMessageDialog(null,"Please fill in the name of the opposistion");
           return false;
       }
       int a,b;
       try{
           a = Integer.parseInt(jTextField2.getText());
           b = Integer.parseInt(jTextField3.getText());
       }
       catch(NumberFormatException nfe ){
           JOptionPane.showMessageDialog(null,"Please fill an integer number");
           return false;
       }
       if(a < 0 || b < 0){
          JOptionPane.showMessageDialog(null,"Please fill an integer number larger than 0");
          return false;
       }
       return true;
    }
    
    
    
    private void getList() throws SQLException{
        PreparedStatement st = null;
        ResultSet rs = null;
        Connection con = MyConnection.getConnection();
        try{
           
            String query = "SELECT * FROM `playertable` ";
            st = con.prepareStatement(query);
            rs = st.executeQuery();
            while(rs.next()!=false){
                String name = rs.getString("name");
                String num = String.valueOf(rs.getInt("num"));
                PlayerList.add(num+"."+" "+ name);
            }
            for(int i = 0;i<PlayerList.size();i++){
                playermodel.addElement(PlayerList.get(i));
            }
           
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Something wrong");
            java.util.logging.Logger.getLogger(MatchPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        finally{
            if(rs!=null){
                try{
                    rs.close();
                }
                catch (SQLException e){
                    
                }
            }
            if(st!=null){
                try{
                    st.close();
                }
                catch (SQLException e){
                    
                }
            }if(con!=null){
                try{
                    con.close();
                }
                catch (SQLException e){
                    
                }
            }
        }

    }
    
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void Sub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(checkRequirement()== false);
        else{
            PreparedStatement st = null;
            ResultSet rs = null;
            Connection con = MyConnection.getConnection();
            try{
            st = con.prepareStatement("INSERT INTO `matchdatabase`(`Opponent`, `HomeAway`, `P1`, `P2`, `P3`, `P4`, `P5`, `P6`, `P7`, `P8`, `P9`, `P10`, `P11`, `Sub1`, `Sub2`, `Sub3`, `Sub4`, `Sub5`, `Sub6`, `Sub7`, `Date`, `SubCount`,`CSubbed1`,`CSubbed2`,`CSubbed3`,`Goal`,`Goaled`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");            
            st.setString(1,jTextField1.getText());
            if(jRadioButton1.isSelected()) st.setString(2,"Home");
            else st.setString(2,"Away");
            st.setInt(3, getID(P1.getItemAt(P1.getSelectedIndex())));
            st.setInt(4, getID(P2.getItemAt(P2.getSelectedIndex())));
            st.setInt(5, getID(P3.getItemAt(P3.getSelectedIndex())));
            st.setInt(6, getID(P4.getItemAt(P4.getSelectedIndex())));
            st.setInt(7, getID(P5.getItemAt(P5.getSelectedIndex())));
            st.setInt(8, getID(P6.getItemAt(P6.getSelectedIndex())));
            st.setInt(9, getID(P7.getItemAt(P7.getSelectedIndex())));
            st.setInt(10, getID(P8.getItemAt(P8.getSelectedIndex())));
            st.setInt(11, getID(P9.getItemAt(P9.getSelectedIndex())));
            st.setInt(12, getID(P10.getItemAt(P10.getSelectedIndex())));
            st.setInt(13, getID(P11.getItemAt(P11.getSelectedIndex())));
            st.setInt(14, getID(PS1.getItemAt(PS1.getSelectedIndex())));
            st.setInt(15, getID(PS2.getItemAt(PS2.getSelectedIndex())));
            st.setInt(16, getID(PS3.getItemAt(PS3.getSelectedIndex())));
            st.setInt(17, getID(PS4.getItemAt(PS4.getSelectedIndex())));
            st.setInt(18, getID(PS5.getItemAt(PS5.getSelectedIndex())));
            st.setInt(19, getID(PS6.getItemAt(PS6.getSelectedIndex())));
            st.setInt(20, getID(PS7.getItemAt(PS7.getSelectedIndex())));
            LocalDate now = LocalDate.now();
            String date = now.toString();
            st.setString(21, date);
            st.setInt(22,SubCount);
            for(int i = 0;i<SubCount;i++){
                int a  = 23 + i;
                st.setInt(a,Sub.get(i));
            }
            if(SubCount < 1) st.setString(23,"0");
            if(SubCount < 2) st.setString(24,"0");
            if(SubCount < 3) st.setString(25,"0");
            st.setInt(26,Integer.parseInt(jTextField2.getText()));
            st.setInt(27,Integer.parseInt(jTextField3.getText()));

            if(st.executeUpdate()!=0) System.out.println("Success");  
            }
            catch (SQLException ex){
                JOptionPane.showMessageDialog(null,"Something wrong");
                java.util.logging.Logger.getLogger(MatchPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            finally{
            if(rs!=null){
                try{
                    rs.close();
                }
                catch (SQLException e){
                    
                }
            }
            if(st!=null){
                try{
                    st.close();
                }
                catch (SQLException e){
                    
                }
            }if(con!=null){
                try{
                    con.close();
                }
                catch (SQLException e){
                    
                }
            }
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public int getID(String a){
        int id = 0;
        char[] ch = a.toCharArray();
        if(Character.toString(ch[1]).equals(".") ){
            id = Integer.parseInt(Character.toString(ch[0]));  
            }
            else{
            id = Integer.parseInt(Character.toString(ch[0])+Character.toString(ch[1]));
                    };
        return id;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatchPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatchPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatchPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatchPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MatchPlayer().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MatchPlayer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> P1;
    private javax.swing.JComboBox<String> P10;
    private javax.swing.JComboBox<String> P11;
    private javax.swing.JComboBox<String> P2;
    private javax.swing.JComboBox<String> P3;
    private javax.swing.JComboBox<String> P4;
    private javax.swing.JComboBox<String> P5;
    private javax.swing.JComboBox<String> P6;
    private javax.swing.JComboBox<String> P7;
    private javax.swing.JComboBox<String> P8;
    private javax.swing.JComboBox<String> P9;
    private javax.swing.JComboBox<String> PS1;
    private javax.swing.JComboBox<String> PS2;
    private javax.swing.JComboBox<String> PS3;
    private javax.swing.JComboBox<String> PS4;
    private javax.swing.JComboBox<String> PS5;
    private javax.swing.JComboBox<String> PS6;
    private javax.swing.JComboBox<String> PS7;
    private javax.swing.JComboBox<String> Pos1;
    private javax.swing.JComboBox<String> Pos10;
    private javax.swing.JComboBox<String> Pos11;
    private javax.swing.JComboBox<String> Pos2;
    private javax.swing.JComboBox<String> Pos3;
    private javax.swing.JComboBox<String> Pos4;
    private javax.swing.JComboBox<String> Pos5;
    private javax.swing.JComboBox<String> Pos6;
    private javax.swing.JComboBox<String> Pos7;
    private javax.swing.JComboBox<String> Pos8;
    private javax.swing.JComboBox<String> Pos9;
    private javax.swing.JRadioButton Sub1;
    private javax.swing.JRadioButton Sub2;
    private javax.swing.JRadioButton Sub3;
    private javax.swing.JRadioButton Sub4;
    private javax.swing.JRadioButton Sub5;
    private javax.swing.JRadioButton Sub6;
    private javax.swing.JRadioButton Sub7;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables

}
